"""Generate a Home Assistant dashboard from the register definitions.

The heat pump publishes well over a hundred entities. Assembling them into something
readable by hand is an afternoon's work that has to be redone whenever the definitions
change, so the dashboard is generated from the same file the entities come from - the
way ThermIQ ships a dashboard with its integration rather than a list of entity names.

    ./dev-cli.py dashboard

Writes ha-dashboard.yaml, which is pasted into Home Assistant with
Settings -> Dashboards -> Add dashboard -> ... -> Raw configuration editor.
"""

import logging

from cli_base.cli_tools.verbosity import setup_logging
from cli_base.tyro_commands import TyroVerbosityArgType
from ha_services.mqtt4homeassistant.utilities.string_utils import slugify

from kronoterm2mqtt.cli_dev import PACKAGE_ROOT, app
from kronoterm2mqtt.user_settings import HeatPump


logger = logging.getLogger(__name__)

DASHBOARD_PATH = PACKAGE_ROOT / 'ha-dashboard.yaml'

# Which entities belong on which card, matched against the definition's name. Order
# decides the order on the dashboard; anything unmatched lands in "Everything else", so
# a new register shows up somewhere instead of disappearing.
CARDS = (
    ('Sanitary water', ('DHW', 'sanitary')),
    ('Buffer tank', ('buffer',)),
    ('Heating loops', ('loop',)),
    ('Heat source', ('source', 'compressor', 'evaporator', 'condens')),
    ('Power and energy', ('power', 'energy', 'COP', 'current')),
    ('Operating hours', ('hours', 'operating time')),
    ('Errors and warnings', ('error', 'warning', 'alarm')),
)


def entity_id(domain: str, device_name: str, name: str) -> str:
    """What Home Assistant calls the entity that MQTT discovery created."""
    return f'{domain}.{slugify(device_name, "_").lower()}_{slugify(name, "_").lower()}'


def card_for(name: str) -> str:
    lowered = name.lower()
    for title, keywords in CARDS:
        if any(keyword.lower() in lowered for keyword in keywords):
            return title
    return 'Everything else'


def build(device_name: str = 'Heat Pump', definitions: dict | None = None) -> dict:
    definitions = definitions if definitions is not None else HeatPump().get_definitions(verbosity=0)

    domains = (
        ('number', 'number'),
        ('switch', 'switch'),
        ('select', 'select'),
        ('sensor', 'sensor'),
        ('enum_sensor', 'sensor'),
        ('binary_sensor', 'binary_sensor'),
    )

    grouped: dict[str, list[str]] = {}
    seen: set[str] = set()
    for section, domain in domains:
        for parameter in definitions.get(section, []):
            entity = entity_id(domain, device_name, parameter['name'])
            if entity in seen:
                continue
            seen.add(entity)
            grouped.setdefault(card_for(parameter['name']), []).append(entity)

    # Settings first: those are the entities anyone opens the dashboard to change.
    order = ['Sanitary water', 'Buffer tank', 'Heating loops', 'Heat source']
    order += [title for title, _ in CARDS if title not in order]
    order += ['Everything else']

    cards = [{'type': 'entities', 'title': title, 'entities': grouped[title]} for title in order if grouped.get(title)]
    return {
        'views': [
            {
                'title': 'Heat pump',
                'path': 'heat-pump',
                'icon': 'mdi:heat-pump',
                'cards': cards,
            }
        ]
    }


def render(dashboard: dict) -> str:
    """A small YAML writer: the structure is known, and this keeps the output stable."""
    lines = [
        '# Generated by ./dev-cli.py dashboard - edit the definitions, not this file.',
        '#',
        '# Home Assistant: Settings -> Dashboards -> Add dashboard -> Ctrl+A, paste.',
        '# Entity names assume [heat_pump] device_name = "Heat Pump"; change the prefix',
        '# if yours differs.',
        'views:',
    ]
    for view in dashboard['views']:
        lines.append(f'  - title: {view["title"]}')
        lines.append(f'    path: {view["path"]}')
        lines.append(f'    icon: {view["icon"]}')
        lines.append('    cards:')
        for card in view['cards']:
            lines.append(f'      - type: {card["type"]}')
            lines.append(f'        title: {card["title"]}')
            lines.append('        entities:')
            lines.extend(f'          - {entity}' for entity in card['entities'])
    return '\n'.join(lines) + '\n'


@app.command
def dashboard(verbosity: TyroVerbosityArgType):
    """
    Generate ha-dashboard.yaml from the register definitions
    """
    setup_logging(verbosity=verbosity)
    DASHBOARD_PATH.write_text(render(build()), encoding='UTF-8')
    print(f'Wrote {DASHBOARD_PATH}')
